version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ../:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: kkadb
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: karan@123
            MYSQL_DATABASE: epiz_32211115_quiska
        ports:
            - "3306:3306"